### ISSUE TITLE
BackEnd: API  DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL 

### ISSUE THREAD

**Issue by iztok-gregori** [Calipsoplus/calipsoplus-backend#27]
When enabling the REST API for the DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL we notice that the GET request path is:

"GET /experiments/iztok.gregori/?page=1&ordering= HTTP/1.1"

The request cannot be served because the URL is not valid on our remote server. So:

- The /experiments part should be customizable to reflect the structure of the remote endpoint
- The username should be a plain GET parameter (not part of the url path), at least as an option.

**Comment by acampsm** [comment]
_when DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL=1_

It uses a call to ... DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL_ENDPOINT

**from the frontend is:**
`get  CALIPSO_BACKEND_URL/experiments/auo-drboer/?page=1&ordering=`

**from the backend to the service makes a get to DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL_ENDPOINT**
the source code in backend:
```
query = {"page_size": PAGE_SIZE_EXPERIMENTS,
                         "page": request.GET.get('page'),
                         "ordering": request.GET.get('ordering'),
                         "search": request.GET.get('search'),
                         "calipsouserexperiment__favorite": request.GET.get('calipsouserexperiment__favorite')}

url = settings.DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL_ENDPOINT.replace('$USERNAME', username)

response = requests.get(url, params=query, auth=(
                settings.LOCAL_ACCESS_USERNAME, settings.LOCAL_ACCESS_PASSWORD))
```
I hope this helps.

**Comment by iztok-gregori** [comment]
Hi!

Our **DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL_ENDPOINT** is 

https://vuo.elettra.eu/pls/vuo/vuo_calipso.get_experiments

but the backend is accessing:

https://vuo.elettra.eu/experiments/<username>

The **/experiments** part of the URL above is defined in urls.py. Can we change it without interfering with other "sutff"?

**Comment by dsanchez-cells** [comment]
Hi Iztok,
The urls.py defines only the Calipso (django) backend endpoints, it does not affect which endpoint the backend itself is accessing. Would you prefer to discuss this via Slack? I'd like to know better what problem there is at your end.

**Comment by acampsm** [comment]
You need to add **$USERNAME** in the endpoint to de service url
DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL_ENDPOINT = 
https://data.domain.tld/services/experiments/$USERNAME/
The backend changes to username

**Comment by iztok-gregori** [comment]
> You need to add **$USERNAME** in the endpoint to de service url
> DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL_ENDPOINT =
> https://data.domain.tld/services/experiments/$USERNAME/
> The backend changes to username

This did the work, thank you!
The documentation should be updated IMHO
