### ISSUE TITLE
Get UID and GID from user/experiment: User Office REST API

### ISSUE THREAD

**Issue by acampsm** [Calipsoplus/calipsoplus-backend#29]
We have to add two more fields into experiments table. 

These fields are account_uid, account_gid. These could be retrieved from the external API or from DB. 

Now when the user launches a new resource we will pass these values as a parameter with the volume  to keep the same folder permissions.

**Comment by aicampbell** [comment]
Please assign this to me as I have already been working on it

**Comment by acampsm** [comment]
I think this issue is done already. Could we close it?
