### ISSUE TITLE
Create testing configuration to run on a single server

### ISSUE THREAD

**Issue by aicampbell** [Calipsoplus/calipsoplus-backend#47]
Need testing environment like Travis which uses a single virtual machine to run all tests.

Might be possible to set backend and frontend ip address to 0.0.0.0 in the unit test configuration

**Comment by aicampbell** [comment]
Most tests pass but we need to stub Docker when creating a container

**Comment by acampsm** [comment]
How could we do that?

**Comment by aicampbell** [comment]
For now, you could split up the tests into unit tests and integration tests.
Unit tests should be able to run with only one machine.
Integration tests should use multiple machines or we mock them.

Take a look here:
https://github.com/docker/docker-py/tree/master/tests
