### ISSUE TITLE
Adding CPU, RAM and HDD values to container model

### ISSUE THREAD

**Issue by aicampbell** [Calipsoplus/calipsoplus-backend#57]
Collecting data on these allow for usage statistics  on the Docker machine / kubernetes cluster. Useful for admin section too.

These values are already stored in the container image but there is no link between the container and the image being run inside it. We could do something like:

`new_container.cpu = selected_image.cpu`
`new_container.memory = selected_image.memory`
`new_container.hdd = selected_image.hdd`

Additional possible use case to consider: 
Allow scientists/users to create a container with custom CPU and RAM resources providing they do not exceed their quota.

**Comment by aicampbell** [comment]
@acampsm @dsanchez-cells 

What do you think of this suggestion?
We can add it to another branch before the deliverable

**Comment by acampsm** [comment]
The container model are the resources that are ready to use (status=created).
Each container launch an image that has a cost with hdd, memory,.. 
There are also a quota table that is the maximum quota per user.
And also in settings there is a generic quota if the user dosent have in the quota table.
When resource_docker is launched , it runs the docker container with this parameters.

So.. do you mean that when the user launch a resource, they could select specific cost for him that overrides the cost of this image?

**Comment by aicampbell** [comment]
I have two points:

1. Being able to do statistics on a container so we can determine the amount of CPU and RAM it is using. Currently, I don't see anyway of doing this right now. There was no connection between the container and the image in the database

2. On the resource page only, allow scientists/users to select the image, but allow them to override the cost of the image as long as it does not exceed the quota. IF they choose not to override, then we use the cost of the image
